#!/usr/bin/env sh
set -eu

if ! command -v pre-commit >/dev/null 2>&1; then
  printf '\033[31mError:\033[0m pre-commit is not installed on the host.\n' >&2
  printf 'Run: \033[1mpip install pre-commit\033[0m or install it into your local virtualenv.\n' >&2
  exit 1
fi

exec pre-commit run --all-files
#exec pre-commit run --hook-stage pre-commit
